evaluate_task:
  description: >
    Evaluate {news} about {topic}. 
    Make use of your tools to research on Google also any RELEVANT information, given the current year is {current_year}.
    If you can't find any RELEVANT information after your research, conclude that the information is unverifiable.
    DON'T try to search news endlessly.
  expected_output: >
    The answer "yes" or "no" about the goodness of {news}, 
    coming with an explanation of why you think so, citing every website source (if any).
    Formatted as markdown.
  agent: domain_expert
  markdown: True
  output_file: outputs/expert_review.md

_verdict_task_common: &verdict
  expected_output: >
    Your verdict "True" or "Fake" about {news}, 
    coming with an explanation of why you think so.
    Formatted as markdown.
  expected_output: >
    Your verdict "True" or "Fake" about {news}, 
    coming with an explanation of why you think so.
    Formatted as markdown.

left_wing_verdict_task:
  description: >
    Decide if {news} is real or no.
    Remember to consider the expert domain's opinion, but to base the decision also on your
    LEFT WING political views
  <<: *verdict
  agent: left_wing_judge
  output_file: outputs/left_verdict.md

right_wing_verdict_task:
  description: >
    Decide if {news} is real or no.
    Remember to consider the expert domain's opinion, but to base the decision also on your
    RIGHT WING political views
  <<: *verdict
  agent: right_wing_judge
  output_file: outputs/right_verdict.md

neutral_verdict_task:
  description: >
    Decide if {news} is real or no.
    Remember to consider the expert domain's opinion, but to base the decision also on your opinion
  <<: *verdict
  agent: neutral_judge
  output_file: outputs/neutral_verdict.md

influenced_verdict_task:
  description: >
    Decide if {news} is real or no, based entirely on what the domain's expert says
  <<: *verdict
  agent: influenced_judge
  output_file: outputs/influenced_verdict.md

self_centered_verdict_task:
  description: >
    Decide if {news} is real or no, based entirely on what's your opinion on it.
  <<: *verdict
  agent: self_centered_judge
  output_file: outputs/self_centered_verdict.md

decision_task:
  description: >
    Collect the opinion of every judge, counting yes and no to provide the final decision on {news}
  expected_output: >
    The answer "TRUTH" or "FAKE" about {news}, explaining briefly which judge voted yes and which voted no
    Formatted as markdown.
  agent: decision_agent
  markdown: True
  output_file: outputs/final_sentence.md